### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by SevereOverfl0w** [any1/aml#6]
Hi, in order to package wayvnc, I need a tagged release of aml to add to the repo.  Would you be able to cut a 0.1.0?

**Comment by any1** [comment]
I might actually do a proper release of everything very soon. Out of curiosity, which distro are you packaging for?

**Comment by any1** [comment]
There is now a tag, but you might want to wait until I've released neatvnc and wayvnc.

**Comment by SevereOverfl0w** [comment]
I'm packaging guy for void Linux. I'll wait for a neat and way release. I have both building from master right now though (but I can't contribute that upstream)
